# Generated by Django 4.2.6 on 2023-11-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=255)),
                ('NPM', models.IntegerField(null=True)),
                ('TANGGAL_LAHIR', models.DateField(null=True)),
                ('UNIVERSITAS', models.CharField(max_length=255)),
            ],
        ),
    ]
