# Generated by Django 4.2.6 on 2023-11-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=255)),
                ('Alamat', models.TextField()),
                ('Profesi', models.CharField(max_length=255)),
            ],
        ),
    ]
